//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBWorker.DAL.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Malfunction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Malfunction()
        {
            this.UserServiceLinks = new HashSet<UserServiceLink>();
            this.FixIssues = new HashSet<FixIssue>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public System.DateTime AppearsDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserServiceLink> UserServiceLinks { get; set; }
        public virtual RAMMulfunctions RAMMulfunction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FixIssue> FixIssues { get; set; }
    }
}
