//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBWorker.DAL.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class RAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RAM()
        {
            this.RAMMedias = new HashSet<RAMMedia>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int Size { get; set; }
        public System.DateTime PruductionDate { get; set; }
        public Nullable<int> MemoryFrequency { get; set; }
        public string UsePropose { get; set; }
        public bool IsBuffered { get; set; }
        public System.DateTime Warranty { get; set; }
    
        public virtual Manufacturer Manufacturer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RAMMedia> RAMMedias { get; set; }
        public virtual RAMMulfunctions RAMMulfunction { get; set; }
    }
}
