//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBWorker.DAL.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class RAMMedia
    {
        public int Id { get; set; }
        public string Data { get; set; }
    
        public virtual RAM RAM { get; set; }
        public virtual RAMMediaType RAMMediaType { get; set; }
    }
}
