//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBWorker.DAL.EDM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RamMalfunctionsModelContainer : DbContext
    {
        public RamMalfunctionsModelContainer()
            : base("name=RamMalfunctionsModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<RAM> RAMs { get; set; }
        public virtual DbSet<Manufacturer> Manufacturers { get; set; }
        public virtual DbSet<RAMMediaType> RAMMediaTypes { get; set; }
        public virtual DbSet<UserServiceLink> UserServiceLinks { get; set; }
        public virtual DbSet<RAMMedia> RAMMedias { get; set; }
        public virtual DbSet<Malfunction> Malfunctions { get; set; }
        public virtual DbSet<RAMMulfunctions> RAMMulfunctions { get; set; }
        public virtual DbSet<FixIssue> FixIssues { get; set; }
    }
}
